/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define LIBDV_HAVE_LIBPOPT 0

#define LIBDV_LITTLE_ENDIAN_BITFIELD

#define LIBDV_USING_ASM 0

